#pragma once

// ==============================================================================
// Version Information (AUTO-GENERATED - DO NOT EDIT)
// ==============================================================================
// This file is generated by CMake from version.h.in
// Edit version.json to change version numbers and metadata.
// ==============================================================================

#define MAJOR_VERSION_STR "0"
#define MAJOR_VERSION_INT 0

#define SUB_VERSION_STR "8"
#define SUB_VERSION_INT 8

#define RELEASE_NUMBER_STR "0"
#define RELEASE_NUMBER_INT 0

#define BUILD_NUMBER_STR "1"
#define BUILD_NUMBER_INT 1

#define FULL_VERSION_STR MAJOR_VERSION_STR "." SUB_VERSION_STR "." RELEASE_NUMBER_STR "." BUILD_NUMBER_STR

#define VERSION_STR MAJOR_VERSION_STR "." SUB_VERSION_STR "." RELEASE_NUMBER_STR

// UI display version (e.g., "Iterum v0.1.2")
#define UI_VERSION_STR "Iterum v" VERSION_STR

#define stringPluginName "Iterum"
#define stringOriginalFilename "Iterum.vst3"
#define stringFileDescription "Iterum VST3 Delay Plugin"
#define stringCompanyName "Krate Audio"
#define stringVendorURL "https://github.com/rolandzwaga/iterum"
#define stringVendorEmail "rbzwaga@gmail.com"
#define stringLegalCopyright "Copyright (c) 2025 Krate Audio"
#define stringLegalTrademarks ""
