// ==============================================================================
// Factory kit preset round-trip test.
//
// The resources/presets/Kit Presets/*.memkit files are generated by
// tools/gen_factory_presets.js. After unifying the state codec, this test
// guards that every factory preset on disk is readable by the current codec
// and round-trips bit-exact through read -> write.
// ==============================================================================

#include <catch2/catch_test_macros.hpp>

#include "state/state_codec.h"

#include "public.sdk/source/common/memorystream.h"
#include "pluginterfaces/base/ibstream.h"

#include <cstdint>
#include <filesystem>
#include <fstream>
#include <vector>

using namespace Steinberg;
using Membrum::State::KitSnapshot;
using Membrum::State::readKitBlob;
using Membrum::State::writeKitBlob;

namespace {

std::vector<std::uint8_t> readFile(const std::filesystem::path& p)
{
    std::ifstream in(p, std::ios::binary);
    if (!in)
        return {};
    in.seekg(0, std::ios::end);
    const auto size = static_cast<std::streamsize>(in.tellg());
    in.seekg(0, std::ios::beg);
    std::vector<std::uint8_t> buf(static_cast<std::size_t>(size));
    if (size > 0)
        in.read(reinterpret_cast<char*>(buf.data()), size);
    return buf;
}

std::filesystem::path factoryPresetRoot()
{
    // The test binary runs from build/.../bin/Release, so walk up to find
    // plugins/membrum/resources/presets/Kit Presets.
    auto cur = std::filesystem::current_path();
    for (int i = 0; i < 8; ++i)
    {
        const auto candidate =
            cur / "plugins" / "membrum" / "resources" / "presets" / "Kit Presets";
        if (std::filesystem::exists(candidate))
            return candidate;
        if (!cur.has_parent_path() || cur.parent_path() == cur)
            break;
        cur = cur.parent_path();
    }
    return {};
}

} // namespace

TEST_CASE("Factory kit presets: every .memkit under resources/ round-trips "
          "through the state codec",
          "[membrum][preset][factory][kit_preset]")
{
    const auto root = factoryPresetRoot();
    if (root.empty())
    {
        WARN("Factory preset root not found -- skipping (CI build running "
             "from an unexpected working directory).");
        return;
    }

    int count = 0;
    for (const auto& entry : std::filesystem::recursive_directory_iterator(root))
    {
        if (!entry.is_regular_file() || entry.path().extension() != ".memkit")
            continue;

        INFO("factory preset: " << entry.path().string());
        const auto bytes = readFile(entry.path());
        REQUIRE(!bytes.empty());

        // Read -> KitSnapshot must succeed.
        MemoryStream stream;
        int32 written = 0;
        stream.write(const_cast<std::uint8_t*>(bytes.data()),
                     static_cast<int32>(bytes.size()), &written);
        stream.seek(0, IBStream::kIBSeekSet, nullptr);

        KitSnapshot kit;
        REQUIRE(readKitBlob(&stream, kit) == kResultOk);

        // Write back and compare bytes.
        MemoryStream rewrite;
        REQUIRE(writeKitBlob(&rewrite, kit) == kResultOk);
        int64 rewriteSize = 0;
        rewrite.seek(0, IBStream::kIBSeekEnd, &rewriteSize);
        CHECK(static_cast<std::size_t>(rewriteSize) == bytes.size());

        rewrite.seek(0, IBStream::kIBSeekSet, nullptr);
        std::vector<std::uint8_t> rewriteBytes(
            static_cast<std::size_t>(rewriteSize));
        int32 got = 0;
        rewrite.read(rewriteBytes.data(),
                     static_cast<int32>(rewriteSize), &got);
        CHECK(rewriteBytes == bytes);
        ++count;
    }

    // All three factory kits must be present and verified.
    CHECK(count >= 3);
}
