#pragma once

// ==============================================================================
// Plate Mode Constants -- Free-plate Chladni (m + 2n) modal ratios
// ==============================================================================
// Sources:
//   - Chladni, E.F.F. (1802): "Die Akustik" -- the (m + 2n) nodal-figure law.
//   - Rossing, T.D. & Peterson, R.W. (1982/1986): cymbal/gong modal analysis,
//     JASA; Rossing, "Science of Percussion Instruments" Ch.3 (plates/cymbals).
//   - Fletcher, N.H. (1999): "The nonlinear physics of musical instruments".
//   - Leissa, A.W. (1969): "Vibration of Plates" (free circular plate).
//   - Spec 135 "Plate" body reference.
//
// PHYSICS CHANGE (signal-path audit §3-B, "Plate uses SSSS (m^2+n^2)/2 ratios"):
// the previous table used the SIMPLY-SUPPORTED (hinged) square-plate eigenvalues
//   f_{m,n} / f_{1,1} = (m^2 + n^2) / 2
// which describe a plate pinned at all four edges. A struck cymbal/gong has FREE
// edges, so its partials follow Chladni's power law in (m + 2n):
//   f_{m,n} = C * (m + 2n)^P
// where m = nodal DIAMETERS, n = nodal CIRCLES. The SSSS ladder was quasi-regular
// with exact degenerate repeats (12.5 and 25.0 each appeared twice) -- MORE
// ordered than a real inharmonic plate -- so Size/Material/Stretch/Scatter only
// scaled the same skeleton and metallic presets converged on one spectrum.
//
// Implementation notes (honest about what is/ isn't measured):
//   - P = 1.7 is the measured-cymbal Chladni exponent reported by Rossing &
//     Peterson (the classical Kirchhoff exponent is 2; real cymbals sit lower,
//     which also packs the upper partials denser -> shimmer).
//   - Pure (m + 2n)^P leaves exact degeneracies (e.g. (2,0) and (0,1) both have
//     m+2n = 2). A real free plate splits these -- circular-node families are
//     stiffer and sit sharp of the pure power law. We model that with a small
//     per-circular-family term (1 + kappa*n), kappa = 0.11. This is a perceptual
//     fit (like the Stretch B_max range), NOT an exact Leissa eigenvalue table.
//   - Rigid-body modes (0,0) translation and (1,0) tilt are excluded; the
//     fundamental is the (2,0) "two-diameter" mode.
//
// The (m,n) grid and the ratio table are generated together (tools-side
// gen_plate_chladni.js, P=1.7 kappa=0.11) and MUST stay in lock-step: the
// resonator-bank consumers read frequency from kPlateRatios[k] and strike
// amplitude from kPlateIndices[k] (plate_mapper.h / noise_body_mapper.h).
//
// Phase 8B keeps the 48-entry table (6 clean AVX2 kernel iters); Noise Body
// reuses the same arrays (FR-025 / FR-062).
// ==============================================================================

#include <cmath>

namespace Membrum::Bodies {

// Phase 8B: plate mode count 16 -> 48 (6 clean AVX2 kernel iters).
inline constexpr int kPlateModeCount    = 48;
inline constexpr int kPlateMaxModeCount = 48;

struct PlateModeIndices
{
    int m;  // nodal diameters
    int n;  // nodal circles
};

// (m,n) free-plate mode indices, sorted by Chladni value (m+2n)^P*(1+kappa*n).
// Generated by tools gen_plate_chladni.js (P=1.7, kappa=0.11). Fundamental is
// (2,0); rigid-body (0,0)/(1,0) are excluded.
inline constexpr PlateModeIndices kPlateIndices[kPlateMaxModeCount] = {
    {2, 0}, {0, 1}, {3, 0}, {1, 1}, {4, 0}, {2, 1}, {0, 2}, {5, 0},
    {3, 1}, {1, 2}, {6, 0}, {4, 1}, {2, 2}, {7, 0}, {0, 3}, {5, 1},
    {3, 2}, {8, 0}, {1, 3}, {6, 1}, {4, 2}, {9, 0}, {2, 3}, {7, 1},
    {0, 4}, {10, 0}, {5, 2}, {8, 1}, {3, 3}, {11, 0}, {1, 4}, {6, 2},
    {9, 1}, {4, 3}, {12, 0}, {7, 2}, {2, 4}, {10, 1}, {0, 5}, {13, 0},
    {5, 3}, {8, 2}, {3, 4}, {11, 1}, {14, 0}, {6, 3}, {1, 5}, {9, 2},
};

// Mode ratios relative to the (2,0) fundamental = ((m+2n)^P*(1+kappa*n)) norm.
// Lock-step with kPlateIndices above (same generator, same order).
inline constexpr float kPlateRatios[kPlateMaxModeCount] = {
    1.0000f,  1.1100f,  1.9923f,  2.2115f,  3.2490f,  3.6064f,  3.9638f,  4.7479f,
    5.2701f,  5.7924f,  6.4730f,  7.1850f,  7.8971f,  8.4123f,  8.6091f,  9.3377f,
    10.2630f, 10.5561f, 11.1884f, 11.7172f, 12.8784f, 12.8962f, 14.0396f, 14.3148f,
    15.2007f, 15.4258f, 15.7333f, 17.1227f, 17.1519f, 18.1391f, 18.5705f, 18.8195f,
    20.1344f, 20.5164f, 21.0309f, 22.1297f, 22.2132f, 23.3443f, 23.9101f, 24.0964f,
    24.1250f, 25.6577f, 26.1204f, 26.7470f, 27.3317f, 27.9710f, 28.1157f, 29.3976f,
};

/// Strike-position amplitude for free-plate mode (m,n).
///
/// The circular-plate mode shape is  phi(r,theta) = R_{mn}(r) * cos(m*theta)
/// (Leissa; Rossing Ch.3). The strike weight is phi evaluated at the strike
/// point. The single user-facing Strike Position scalar is mapped to a 2-D point
/// that sweeps BOTH the radius and the azimuth, so every (m,n) mode -- including
/// the axisymmetric m=0 ring modes -- responds to the knob:
///   rho   = 0.40 + 0.50 * strikePos      -> [0.40, 0.90] radius fraction
///   theta = strikePos * (pi / 2)         -> azimuth sweep
/// Radial factor cos(n*pi*rho) gives n nodal circles with an antinode at the
/// FREE edge (rho = 1 -> |cos(n*pi)| = 1), unlike the old simply-supported model
/// that forced a node there. (This supersedes the rectangular SSSS diagonal-sweep
/// hack from correctness-audit Finding 8: the free-plate cos(m*theta) factor with
/// a non-trivial azimuth sweep excites every mode without the y0-node pathology.)
[[nodiscard]] inline float computePlateAmplitude(int modeIdx,
                                                 float strikePos) noexcept
{
    if (modeIdx < 0 || modeIdx >= kPlateMaxModeCount)
        return 0.0f;
    const PlateModeIndices idx = kPlateIndices[modeIdx];
    constexpr float kPi = 3.14159265358979f;
    const float rho   = 0.40f + 0.50f * strikePos;   // radius fraction
    const float theta = strikePos * (kPi * 0.5f);     // azimuth sweep
    const float fm = static_cast<float>(idx.m);
    const float fn = static_cast<float>(idx.n);
    return std::cos(fm * theta) * std::cos(fn * kPi * rho);
}

} // namespace Membrum::Bodies
