#pragma once

// ==============================================================================
// Version Information (AUTO-GENERATED - DO NOT EDIT)
// ==============================================================================
// This file is generated by CMake from version.h.in
// Edit version.json to change version numbers and metadata.
// ==============================================================================

#define MAJOR_VERSION_STR "1"
#define MAJOR_VERSION_INT 1

#define SUB_VERSION_STR "6"
#define SUB_VERSION_INT 6

#define RELEASE_NUMBER_STR "0"
#define RELEASE_NUMBER_INT 0

#define BUILD_NUMBER_STR "1"
#define BUILD_NUMBER_INT 1

#define FULL_VERSION_STR MAJOR_VERSION_STR "." SUB_VERSION_STR "." RELEASE_NUMBER_STR "." BUILD_NUMBER_STR

#define VERSION_STR MAJOR_VERSION_STR "." SUB_VERSION_STR "." RELEASE_NUMBER_STR

// UI display version (e.g., "Gradus v1.0.0")
#define UI_VERSION_STR "Gradus v" VERSION_STR

#define stringPluginName "Gradus"
#define stringOriginalFilename "Gradus.vst3"
#define stringFileDescription "Gradus VST3 Step Arpeggiator"
#define stringCompanyName "Krate Audio"
#define stringVendorURL "https://rolandzwaga.github.io/krate-audio/gradus/"
#define stringVendorEmail "rbzwaga@gmail.com"
#define stringLegalCopyright "Copyright (c) 2026 Krate Audio"
#define stringLegalTrademarks ""
