#!/usr/bin/env node
// Generates specs/_architecture_/symbols.json — an index of public class/struct definitions
// in the KrateDSP headers (name -> scope, layer, header, line) plus same-scope collisions,
// for fast ODR lookup ("does this name already exist?") before adding a new component.
//
//   node tools/gen-symbols.js            # write the JSON
//   node tools/gen-symbols.js --check     # exit 1 if the committed file is stale
//
// Heuristic (regex + brace-tracked scope stack), NOT a compiler. Caveats:
//  - block comments / raw strings containing braces can perturb scope nesting (rare here);
//  - template partial specializations are skipped.
// Nested classes/structs ARE qualified by their enclosing class scope, so a private nested
// struct in two different classes is NOT reported as a collision. Node only; grep is truth.

const fs = require('fs');
const path = require('path');

const REPO_ROOT = path.resolve(__dirname, '..');
const DSP_INC = path.join(REPO_ROOT, 'dsp', 'include', 'krate', 'dsp');
const OUT_FILE = path.join(REPO_ROOT, 'specs', '_architecture_', 'symbols.json');
const LAYERS = ['core', 'primitives', 'processors', 'systems', 'effects'];

function listHeaders(dir) {
  const out = [];
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) out.push(...listHeaders(full));
    else if (e.name.endsWith('.h')) out.push(full);
  }
  return out;
}

function stripComments(line) {
  return line.replace(/\/\*.*?\*\//g, '').replace(/\/\/.*$/, '');
}

const symbols = [];

for (const header of listHeaders(DSP_INC).sort()) {
  const rel = path.relative(REPO_ROOT, header).split(path.sep).join('/');
  const layer = LAYERS.find((l) => rel.includes(`/dsp/${l}/`)) || 'unknown';
  const lines = fs.readFileSync(header, 'utf8').split(/\r?\n/);

  // Unified scope stack of namespaces AND classes/structs, so nested types are fully
  // qualified. Each entry: { name, depth } where depth is the brace depth of its interior.
  const scopeStack = [];
  let depth = 0;
  let pending = null; // scope opened by the current line, attached when its '{' is seen

  for (let i = 0; i < lines.length; i++) {
    const line = stripComments(lines[i]);

    // namespace opener (qualified allowed: namespace A::B). Exclude aliases / using.
    const ns = line.match(/\bnamespace\s+([A-Za-z_][\w:]*)\s*(\{)?\s*$/);
    if (ns && !/using\s+namespace/.test(line) && !/namespace\s+[\w:]+\s*=/.test(line)) {
      pending = { name: ns[1] };
    }

    // class/struct definition (not a forward decl, not a specialization, not a variable)
    const cs = line.match(/^\s*(class|struct)\s+([A-Za-z_]\w*)\b(.*)$/);
    if (cs) {
      const rest = cs[3].trim();
      const isForwardDecl = /^;/.test(rest);
      const isSpecialization = /^</.test(rest);
      const isDefinition = rest === '' || rest.startsWith('{') || rest.startsWith(':') || rest.startsWith('final');
      if (!isForwardDecl && !isSpecialization && isDefinition) {
        symbols.push({
          name: cs[2],
          kind: cs[1],
          scope: scopeStack.map((n) => n.name).join('::') || '(global)',
          layer,
          header: rel,
          line: i + 1,
        });
        pending = { name: cs[2] }; // this type also opens a scope for its members
      }
    }

    // brace accounting: attach a pending scope when its opening '{' arrives; pop on close
    for (const ch of line) {
      if (ch === '{') {
        depth++;
        if (pending) {
          scopeStack.push({ name: pending.name, depth });
          pending = null;
        }
      } else if (ch === '}') {
        depth--;
        while (scopeStack.length && scopeStack[scopeStack.length - 1].depth > depth) scopeStack.pop();
      }
    }
  }
}

symbols.sort((a, b) => a.name.localeCompare(b.name) || a.header.localeCompare(b.header));

// Collisions: same qualified name (namespace::name) defined in more than one header.
const byQualified = {};
for (const s of symbols) {
  const key = `${s.scope}::${s.name}`;
  (byQualified[key] ||= []).push(s);
}
const collisions = Object.entries(byQualified)
  .filter(([, arr]) => new Set(arr.map((s) => s.header)).size > 1)
  .map(([key, arr]) => ({ qualified: key, definitions: arr.map((s) => `${s.header}:${s.line}`) }))
  .sort((a, b) => a.qualified.localeCompare(b.qualified));

const out = {
  _comment: 'Generated by tools/gen-symbols.js — heuristic ODR lookup index. grep is source of truth.',
  symbol_count: symbols.length,
  collisions,
  symbols,
};

const output = JSON.stringify(out, null, 2) + '\n';

if (process.argv.includes('--check')) {
  const current = fs.existsSync(OUT_FILE) ? fs.readFileSync(OUT_FILE, 'utf8') : '';
  if (current !== output) {
    console.error('specs/_architecture_/symbols.json is stale — run: node tools/gen-symbols.js');
    process.exit(1);
  }
  console.log('symbols.json is up to date.');
} else {
  fs.writeFileSync(OUT_FILE, output);
  console.log(`Wrote specs/_architecture_/symbols.json (${symbols.length} symbols, ${collisions.length} collisions).`);
}
