#pragma once

// ==============================================================================
// Version Information (AUTO-GENERATED - DO NOT EDIT)
// ==============================================================================
// This file is generated by CMake from version.h.in
// Edit CMakeLists.txt to change version numbers.
// ==============================================================================

#define MAJOR_VERSION_STR "0"
#define MAJOR_VERSION_INT 0

#define SUB_VERSION_STR "0"
#define SUB_VERSION_INT 0

#define RELEASE_NUMBER_STR "2"
#define RELEASE_NUMBER_INT 2

#define BUILD_NUMBER_STR "1"
#define BUILD_NUMBER_INT 1

#define FULL_VERSION_STR MAJOR_VERSION_STR "." SUB_VERSION_STR "." RELEASE_NUMBER_STR "." BUILD_NUMBER_STR

#define VERSION_STR MAJOR_VERSION_STR "." SUB_VERSION_STR "." RELEASE_NUMBER_STR

#define stringPluginName "Iterum"
#define stringOriginalFilename "Iterum.vst3"
#define stringFileDescription "Iterum VST3 Delay Plugin"
#define stringCompanyName "Your Company"
#define stringVendorURL "https://yourcompany.com"
#define stringVendorEmail "info@yourcompany.com"
#define stringLegalCopyright "Copyright (c) 2025 Your Company"
#define stringLegalTrademarks ""
